-- Smart Subscription Retention — schema additions
-- Target DB: visionart (MariaDB / MySQL 8+)
-- Idempotent: safe to run multiple times.

-- ──────────────────────────────────────────────────────────────────────────
-- 1. Activity tracking on `users`
-- ──────────────────────────────────────────────────────────────────────────

-- last_login_at: updated by AuthService on every successful login
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS last_login_at DATETIME NULL AFTER updated_at;

-- last_active_at: updated by JwtAuthGuard on every authenticated request
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS last_active_at DATETIME NULL AFTER last_login_at;

-- previous_login_at: tracks the login *before* last_login_at
-- (used to detect "RETURNING" segment: came back after a long gap)
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS previous_login_at DATETIME NULL AFTER last_active_at;

-- locale + marketing opt-in (RGPD)
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS locale VARCHAR(8) NOT NULL DEFAULT 'fr' AFTER previous_login_at;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS marketing_opt_in BOOLEAN NOT NULL DEFAULT TRUE AFTER locale;

CREATE INDEX IF NOT EXISTS idx_users_last_login_at ON users(last_login_at);
CREATE INDEX IF NOT EXISTS idx_users_last_active_at ON users(last_active_at);

-- ──────────────────────────────────────────────────────────────────────────
-- 2. Loyalty programme
-- ──────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS loyalty_points (
  user_id CHAR(36) NOT NULL,
  balance INT NOT NULL DEFAULT 0,
  lifetime_earned INT NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id),
  CONSTRAINT fk_loyalty_points_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS loyalty_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id CHAR(36) NOT NULL,
  type VARCHAR(40) NOT NULL,           -- LOGIN_DAILY, ARTWORK_CREATED, LIKE_RECEIVED, REFERRAL, RENEWAL, REDEMPTION
  delta INT NOT NULL,
  ref_id VARCHAR(64) NULL,             -- artwork id, referrer id, etc.
  metadata JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_loyalty_events_user_id (user_id),
  KEY idx_loyalty_events_created_at (created_at),
  CONSTRAINT fk_loyalty_events_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ──────────────────────────────────────────────────────────────────────────
-- 3. Promo codes (generated by backend, mentioned by LLM)
-- ──────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS promo_codes (
  code VARCHAR(32) NOT NULL,
  segment VARCHAR(32) NOT NULL,          -- segment that issued the code
  user_id CHAR(36) NULL,                 -- if scoped to one user (null = generic)
  discount_pct INT NOT NULL,             -- 0-100
  free_months INT NOT NULL DEFAULT 0,
  valid_until DATETIME NOT NULL,
  max_uses INT NOT NULL DEFAULT 1,
  used_count INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (code),
  KEY idx_promo_codes_user_id (user_id),
  KEY idx_promo_codes_segment (segment),
  KEY idx_promo_codes_valid_until (valid_until),
  CONSTRAINT fk_promo_codes_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ──────────────────────────────────────────────────────────────────────────
-- 4. Retention engine
-- ──────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS retention_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at DATETIME NULL,
  total_users INT NOT NULL DEFAULT 0,
  total_actions INT NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'RUNNING',  -- RUNNING, SUCCESS, FAILED
  summary JSON NULL,
  error_message TEXT NULL,
  PRIMARY KEY (id),
  KEY idx_retention_runs_started_at (started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS retention_actions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  run_id BIGINT UNSIGNED NULL,
  user_id CHAR(36) NOT NULL,
  segment VARCHAR(32) NOT NULL,
  channel VARCHAR(20) NOT NULL,           -- IN_APP, EMAIL, PUSH, MULTI
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
                                          -- PENDING, APPROVED, REJECTED, SENT, FAILED, SKIPPED
  requires_review BOOLEAN NOT NULL DEFAULT FALSE,
  payload JSON NOT NULL,                  -- { subject, preheader, body, cta_label, tone }
  context JSON NOT NULL,                  -- variables used in prompt: firstName, daysAway, ...
  promo_code VARCHAR(32) NULL,
  variant VARCHAR(32) NULL,               -- A/B test bucket
  scheduled_for DATETIME NULL,
  sent_at DATETIME NULL,
  reviewed_by CHAR(36) NULL,
  reviewed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_retention_actions_user_id (user_id),
  KEY idx_retention_actions_user_segment (user_id, segment),
  KEY idx_retention_actions_status (status),
  KEY idx_retention_actions_run_id (run_id),
  KEY idx_retention_actions_sent_at (sent_at),
  CONSTRAINT fk_retention_actions_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_retention_actions_run
    FOREIGN KEY (run_id) REFERENCES retention_runs(id) ON DELETE SET NULL,
  CONSTRAINT fk_retention_actions_promo
    FOREIGN KEY (promo_code) REFERENCES promo_codes(code) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS retention_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  action_id BIGINT UNSIGNED NOT NULL,
  type VARCHAR(20) NOT NULL,              -- DELIVERED, OPENED, CLICKED, CONVERTED, UNSUBSCRIBED, BOUNCED
  metadata JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_retention_events_action_id (action_id),
  KEY idx_retention_events_type (type),
  CONSTRAINT fk_retention_events_action
    FOREIGN KEY (action_id) REFERENCES retention_actions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
