apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: visionart
data:
  NODE_ENV: "production"
  PORT: "3000"
  JWT_EXPIRES_IN: "7d"
  DB_TYPE: "mysql"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_DATABASE: "visionart_db"
  DB_SYNCHRONIZE: "false"
  DB_LOGGING: "false"
