apiVersion: apps/v1
kind: Deployment
metadata:
  name: visionart-backend
  namespace: visionart
  labels:
    app: visionart-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: visionart-backend
  template:
    metadata:
      labels:
        app: visionart-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/jizel14/visionart-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          readinessProbe:
            httpGet:
              path: /api
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 30
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      imagePullSecrets:
        - name: ghcr-secret
